In [31]:
# IMPORT LIBRARIES
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical
import matplotlib.pyplot as plt 
import matplotlib.image as img 

In [23]:
# LOAD AND PRE-PROCESS THE MNIST DATASET
(x_train, y_train), (x_test, y_test)= mnist.load_data()

In [24]:
# NORMALIZE THE DATA
x_train = x_train / 255.0
x_test = x_test / 255.0

#FLATTEN THE IMAGES INTO 1-D ARRAY
x_train = x_train.reshape((x_train.shape[0],-1))
x_test = x_test.reshape((x_test.shape[0],-1))

# ONE-HOT ENCODE THE TARGET LABELS
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)


In [25]:
# BUILDING MLP MODEL
model = Sequential()
model.add(Dense(128, input_shape=(784,), activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(10, activation='softmax'))

# COMPILING THE MODEL
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


# TRAIN THE MODEL
model.fit(x_train,y_train,epochs=10,batch_size=32,validation_split=0.2)

Epoch 1/10
1500/1500 [==============================] - 4s 2ms/step - loss: 0.2676 - accuracy: 0.9215 - val_loss: 0.1455 - val_accuracy: 0.9570
Epoch 2/10
1500/1500 [==============================] - 3s 2ms/step - loss: 0.1100 - accuracy: 0.9666 - val_loss: 0.1082 - val_accuracy: 0.9668
Epoch 3/10
1500/1500 [==============================] - 3s 2ms/step - loss: 0.0769 - accuracy: 0.9765 - val_loss: 0.1052 - val_accuracy: 0.9664
Epoch 4/10
1500/1500 [==============================] - 3s 2ms/step - loss: 0.0565 - accuracy: 0.9815 - val_loss: 0.0938 - val_accuracy: 0.9722
Epoch 5/10
1500/1500 [==============================] - 3s 2ms/step - loss: 0.0463 - accuracy: 0.9847 - val_loss: 0.0993 - val_accuracy: 0.9713
Epoch 6/10
1500/1500 [==============================] - 3s 2ms/step - loss: 0.0368 - accuracy: 0.9876 - val_loss: 0.0962 - val_accuracy: 0.9751
Epoch 7/10
1500/1500 [==============================] - 3s 2ms/step - loss: 0.0305 - accuracy: 0.9899 - val_loss: 0.1025 - val_accuracy:

In [26]:
# EVALUATE THE MODEL ON TEST SET
loss, accuracy = model.evaluate(x_test, y_test)
print(f'Test Accuracy: {accuracy*100:.2f}%')

313/313 [==============================] - 0s 838us/step - loss: 0.1007 - accuracy: 0.9740
Test Accuracy: 97.40%


In [27]:
print(x_train)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [28]:
print(y_train)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [38]:
print(x_test.shape)

(10000, 784)


In [40]:
print(model.summary())

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_10 (Dense)            (None, 128)               100480    
                                                                 
 dense_11 (Dense)            (None, 64)                8256      
                                                                 
 dense_12 (Dense)            (None, 10)                650       
                                                                 
Total params: 109,386
Trainable params: 109,386
Non-trainable params: 0
_________________________________________________________________
None
